### ISSUE TITLE
[Bug]: Issues with "Enhance" Feature and "Respect Provider Choice from UI" After Latest Update

### ISSUE THREAD

**Issue by champ2050** [stackblitz-labs/bolt.diy#245]
### Describe the bug

**Description:**  
After updating the repository, two issues have surfaced:

1. **Enhance Feature Not Working**  
   When I type a prompt (e.g., to create a basic "Hello World" HTML page) and click "enhance," the prompt disappears, preventing further progress. This has occurred consistently across multiple attempts.

2. **Model Provider Changes on Project Reload**  
   When reopening older projects, I’ve noticed that the model provider setting does not persist. Instead, it defaults to a different model rather than the one I initially selected, which affects continuity and usability. Ideally, the model provider should remain as originally chosen for each project.

**Actual Behavior:**  
- The prompt disappears when "enhance" is clicked, and no enhanced output is generated.
- Model provider settings reset to a default or different model when reopening a project.

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1. Update the repository to the latest version (current as of two hours ago).
2. In a virtual environment (not Docker), enter a prompt to create a simple HTML page.
3. Click "enhance."
4. Observe that the prompt disappears, and enhancement does not proceed.

To observe the model provider issue:
1. Open any previous project where a specific model provider was chosen.
2. Note that the model provider defaults to a different option rather than the one originally selected.

### Expected behavior

- The "enhance" feature should process the prompt as expected, generating the desired output.
- Model provider settings should remain consistent when reopening a project, using the originally selected provider.

### Platform

**Environment Details:**  
- Operating System: Windows 10
- Browser: Chrome Canary
- Node version: v20.18.0
- pnpm version: 9.12.3

### Additional context

**Additional Information:**  
- Previous repo version in use: November 1, 2024.
- Working in a regular virtual environment with pnpm, not Docker.

**Comment by coleam00** [comment]
Fantastic, thank you @champ2050!

**Comment by nandan-dhamma** [comment]
I pulled a few hours ago, and enhance prompt seems to have an issie

provider in  enhancerAction() has
provider: { name: 'OpenAILike', staticModels: [] },

The below hack works, I am sure it is better to be fixed by someone who knows what to do

async function enhancerAction({ context, request }: ActionFunctionArgs) {
  const { message, model, provider: **originalProvider**, apiKeys } = await request.json<{
    message: string;
    model: string;
    provider: **{ name: string };**
    apiKeys?: Record<string, string>;
  }>();

  // Extract provider.name and reassign to provider
  **const provider = originalProvider.name;**

**Comment by nandan121** [comment]
I pulled a few hours ago, and enhance prompt seems to have an issie

provider in  enhancerAction() has
provider: { name: 'OpenAILike', staticModels: [] },

The below hack works, I am sure it is better to be fixed by someone who knows what to do

async function enhancerAction({ context, request }: ActionFunctionArgs) {
  const { message, model, provider: **originalProvider**, apiKeys } = await request.json<{
    message: string;
    model: string;
    provider: **{ name: string };**
    apiKeys?: Record<string, string>;
  }>();

  // Extract provider.name and reassign to provider
  **const provider = originalProvider.name;**

**Comment by nandan121** [comment]
@champ2050 , I tested fix by ali00209 (new_bolt6 branch). Enhance prompt works as expected

**Comment by coleam00** [comment]
Thanks guys!
