### ISSUE TITLE
Using a Remote VM instead of a WebContainer removing Node.JS limits.

### ISSUE THREAD

**Issue by MadeInLondon** [stackblitz-labs/bolt.diy#594]
**Is your feature request related to a problem? Please describe:**

I have found a problem in the limitations of Bolt.New where due to the WebContainer & the WebAssembly but it limits the potential of this project to JavaScript wrapped packaged.

**Describe the solution you'd like:**

If we can convert the WebContainer to use a VM instead, we can create a version control system by snapshotting the VM. It will also remove all the limits on the LLM to only focus writing in Node.JS. This will also keep the host system secure in case Bolt.New installs packages that compromises the system.

**Describe alternatives you've considered:**

I have used AI to look for alternatives but interested to hear what the community thinks and how this could be implemented without breaking the code. I am aware this may require a code structure change and a way it communicate with API calls.  

**Additional context:**

IDEAS
https://github.com/docker/machine
https://www.virtualbox.org/

**Comment by kustomzone** [comment]
There was a discussion about this a month back on the forum:  [thinktank](https://thinktank.ottomator.ai/t/dependency-on-the-original-bolt-new-repo/113/9)

As discussed, replacing webcontainer with WebVM or similar may be required as Bolt's container is under restricted commercial license. Cole was in discussion with the founder of Bolt a few weeks ago, so we are due to hear something in the coming days on that particular topic, at least according to the devs on the forum.

**Comment by ReEnvisionAi** [comment]
What is the status on this? and what was the duplicate issue?

**Comment by trevorobrien** [comment]
Any progress on this topic?

**Comment by thecodacus** [comment]
currently not in the development pipeline. and is put into future backlog

**Comment by jjstory24** [comment]
using https://github.com/AntonOsika/gpt-engineer in the backend instead of webcontaner will resolve it.

**Comment by thecodacus** [comment]
thats basically lovable
