### ISSUE TITLE
files are not created are just rendered on screen for any model other then sonnet.

### ISSUE THREAD

**Issue by syberkitten** [stackblitz-labs/bolt.diy#666]
### Describe the bug

very few models except sonnet 3.5 actually work.
I get the files rendered on screen and not created.
I also get a lot of ``` at beginning and end of created files (when they are created)

Can someone shed light on this?
The project is completely not usable.

### Link to the Bolt URL that caused the error

https://bolt.new

### Steps to reproduce

should work with many models especially frontier models

### Expected behavior

to work with most frontier models

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Provider Used

google-exp-1206 / gemini-flash / gemini pro

**Comment by Ruglehjs** [comment]
is'n this a prompt problem? sonnet 3.5 is really good at this and as far I know that is the model official bolt is using

**Comment by thecodacus** [comment]
even though we are working on tuning the prompt. its still depends on LLM to follow the prompt. I have seen no problem using other models like gpt4o and event qwen. 
we will be experimenting with prompt variations but wont call this an issue, as there is no guaranteed fix for this.

**Comment by Mugane** [comment]
Why would the model make any difference? The app cannot even generate a simple bash script. It simply won't generate code, instead it is just a chat bot with suggested code like any other chat bot. What is it even designed to do? Why is it not working? Oh, and the whole point of this is to use local models, if none of them work then what is even the point, just use bolt.new.

**Comment by Mugane** [comment]
> Why would the model make any difference? The app cannot even generate a simple bash script. It simply won't generate code, instead it is just renders like a chat bot with suggested code like any other chat bot. What is it even designed to do? Why is it not working? Oh, and the whole point of this is to use local models, if none of them work then what is even the point, just use bolt.new.

**Comment by Agriv8** [comment]
Lol ..rather than mine that does ! …hehe ..


From: Peter Kionga-Kamau ***@***.***>
Date: Thursday, 5 June 2025 at 07:24
To: stackblitz-labs/bolt.diy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [stackblitz-labs/bolt.diy] files are not created are just rendered on screen for any model other then sonnet. (Issue #666)
[Image removed by sender.]Mugane left a comment (stackblitz-labs/bolt.diy#666)<https://github.com/stackblitz-labs/bolt.diy/issues/666#issuecomment-2942921248>

Why would the model make any difference? The app cannot even generate a simple bash script. It simply won't generate code, instead it is just a chat bot with suggested code like any other chat bot. What is it even designed to do? Why is it not working? Oh, and the whole point of this is to use local models, if none of them work then what is even the point, just use bolt.new.

**Comment by Mugane** [comment]
@Agriv8 do you mind removing my personal information from this reply? thanks!

**Comment by Mugane** [comment]
Qwen3:14b-q8_0 seems to manage the prompt constraints, but is very slow. I would love to get a list of local models people have tested that actually work with 16GB VRAM or less...
