### ISSUE TITLE
Add Callback Functionality to Bolt for Scraping Integration

### ISSUE THREAD

**Issue by ihebmrabet** [stackblitz-labs/bolt.diy#780]
I’m looking for a way to add callback functionality to Bolt. Specifically, I want to enable Bolt to:

1. Call a scraping tool that retrieves some text.
2. Use the retrieved text as context for its next generation.

The challenge is that I need a way to call Bolt again from within the code after the scraping tool returns its response.

Does anyone with knowledge of the codebase have suggestions or guidance on how to implement this?

**Comment by ihebmrabet** [comment]
I only need to add a callback to Bolt to utilize the new information. The main problem is that most LLMs are not up-to-date or lack the ability to code effectively. That’s why I integrated a scraping tool to extract documentation for other APIs or packages, enabling Bolt to program more effectively with them. This is why I need the automatic callback to bolt, without requiring the user to provide the informations manually to Bolt.

**Comment by thecodacus** [comment]
If my guess is correct you are looking for knowledge of codebase so that you can edit and integrate your logic.
then here is the answer.
add the response as user message using  the `append` function provided by the `useChat` in `Chat.tsx`  component
once you do that it will act as if user has sent a message. put your data in the message and llm will start responding
